name: Cypress Tests + Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node 18 (OBRIGATÓRIO)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Limpar cache do NPM
        run: npm cache clean --force

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress no modo headless
        run: npx cypress run

      - name: Gerar relatório Allure
        run: npx allure generate allure-results --clean -o allure-report

      - name: Publicar relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
